### ISSUE TITLE
java.lang.IllegalStateException: trying to requery an already closed cursor

### ISSUE THREAD

**Issue by codeguru42** [BaseballCardTracker/bbct#197]
Received crash report on Google Play.

**User Message:** just stopped when my screen timed out

**Device:** PantechP8010

**Android Version:** 4.1

**App Version:** 0.5.6.1

**Stack Trace:**

```
java.lang.IllegalStateException: trying to requery an already closed cursor android.database.sqlite.SQLiteCursor@42b877c0
    at android.app.Activity.performRestart(Activity.java:5051)
    at android.app.ActivityThread.handleSleeping(ActivityThread.java:3113)
    at android.app.ActivityThread.access$2700(ActivityThread.java:138)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4854)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by codeguru42** [comment]
I finally reproduced this issue on my tablet with the following recipe:

1. Select one of the autocomplete fields (Brand, Name, or Team)
2. Enter some text
3. Put device to sleep
4. Wake device up

The next step is to write a UI Automator test that illustrates the issue and verifies when it is fixed.

**Comment by charanyaarvind** [comment]
I am working on Issue172-Take Picture of Cards and I am facing the same issue.
When I fill one of the AutoCompleteTextViews, then start the camera activity to take picture and come back to BaseballCardDetails from camera activity, the app crashes with the same exception.

When I was debugging, I found that there is a 'startManagingCursor' in SingleColumnCursorAdapter:runQueryOnBackgroundThread, but there is no corresponding stopManagingCursor. Is the startManagingCursor necessary there? Would the CursorAdapter's changeCursor take care of it? If we need startManagingCursor, can we call it in changeCursor?
I found this link which may be helpful.
http://stackoverflow.com/questions/12793274/can-someone-explain-to-me-on-runqueryonbackgroundthread

Also, according to android developer manual, the CursorAdapter constructor that is in SingleColumnCursorAdapter is not recommended now. Should that be changed too?

**Comment by codeguru42** [comment]
I have picked up this issue again. I confirmed that the problem is that a Cursor created by `SingleColumnCursorAdapter` is requeried after following the steps in the recipe stated above.

Here are some relevant lines from the logcat of an example run. Note that the cursor address given in the exception error message matches that of the cursor created by the first query.

    01-25 02:46:21.665  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter: runQueryOnBackgroundThread()
    01-25 02:46:21.665  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   constraint=T
    01-25 02:46:21.665  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   projection=[_id, brand]
    01-25 02:46:21.665  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   selection=brand LIKE ?
    01-25 02:46:21.665  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   args=[T%]
    01-25 02:46:21.665  2562  2671 D bbct.android.common.provider.BaseballCardProvider: query()
    01-25 02:46:21.665  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   uri=content://bbct.android.lite.provider/baseball_cards/distinct
    01-25 02:46:21.665  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   projection=[_id, brand]
    01-25 02:46:21.665  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   selection=brand LIKE ?
    01-25 02:46:21.665  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   selectionArgs=[T%]
    01-25 02:46:21.665  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   sortOrder=null
    01-25 02:46:21.681  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   cursor=android.content.ContentResolver$CursorWrapperInner@422677b8
    01-25 02:46:21.681  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:     # of rows=0
    01-25 02:46:21.783  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter: runQueryOnBackgroundThread()
    01-25 02:46:21.783  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   constraint=To
    01-25 02:46:21.783  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   projection=[_id, brand]
    01-25 02:46:21.783  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   selection=brand LIKE ?
    01-25 02:46:21.783  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   args=[To%]
    01-25 02:46:21.783  2562  2671 D bbct.android.common.provider.BaseballCardProvider: query()
    01-25 02:46:21.783  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   uri=content://bbct.android.lite.provider/baseball_cards/distinct
    01-25 02:46:21.783  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   projection=[_id, brand]
    01-25 02:46:21.783  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   selection=brand LIKE ?
    01-25 02:46:21.783  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   selectionArgs=[To%]
    01-25 02:46:21.783  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   sortOrder=null
    01-25 02:46:21.790  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   cursor=android.content.ContentResolver$CursorWrapperInner@422704b8
    01-25 02:46:21.790  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:     # of rows=0
    01-25 02:46:21.806  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter: runQueryOnBackgroundThread()
    01-25 02:46:21.806  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   constraint=Top
    01-25 02:46:21.806  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   projection=[_id, brand]
    01-25 02:46:21.806  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   selection=brand LIKE ?
    01-25 02:46:21.806  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   args=[Top%]
    01-25 02:46:21.806  2562  2671 D bbct.android.common.provider.BaseballCardProvider: query()
    01-25 02:46:21.806  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   uri=content://bbct.android.lite.provider/baseball_cards/distinct
    01-25 02:46:21.806  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   projection=[_id, brand]
    01-25 02:46:21.806  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   selection=brand LIKE ?
    01-25 02:46:21.806  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   selectionArgs=[Top%]
    01-25 02:46:21.806  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   sortOrder=null
    01-25 02:46:21.806  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   cursor=android.content.ContentResolver$CursorWrapperInner@4222afc8
    01-25 02:46:21.806  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:     # of rows=0
    01-25 02:46:21.822  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter: runQueryOnBackgroundThread()
    01-25 02:46:21.822  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   constraint=Topp
    01-25 02:46:21.822  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   projection=[_id, brand]
    01-25 02:46:21.822  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   selection=brand LIKE ?
    01-25 02:46:21.822  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   args=[Topp%]
    01-25 02:46:21.822  2562  2671 D bbct.android.common.provider.BaseballCardProvider: query()
    01-25 02:46:21.822  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   uri=content://bbct.android.lite.provider/baseball_cards/distinct
    01-25 02:46:21.822  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   projection=[_id, brand]
    01-25 02:46:21.822  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   selection=brand LIKE ?
    01-25 02:46:21.822  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   selectionArgs=[Topp%]
    01-25 02:46:21.822  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   sortOrder=null
    01-25 02:46:21.829  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   cursor=android.content.ContentResolver$CursorWrapperInner@42226fe0
    01-25 02:46:21.829  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:     # of rows=0
    01-25 02:46:21.845  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter: runQueryOnBackgroundThread()
    01-25 02:46:21.845  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   constraint=Topps
    01-25 02:46:21.845  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   projection=[_id, brand]
    01-25 02:46:21.845  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   selection=brand LIKE ?
    01-25 02:46:21.845  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   args=[Topps%]
    01-25 02:46:21.845  2562  2671 D bbct.android.common.provider.BaseballCardProvider: query()
    01-25 02:46:21.845  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   uri=content://bbct.android.lite.provider/baseball_cards/distinct
    01-25 02:46:21.845  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   projection=[_id, brand]
    01-25 02:46:21.845  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   selection=brand LIKE ?
    01-25 02:46:21.845  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   selectionArgs=[Topps%]
    01-25 02:46:21.845  2562  2671 D bbct.android.common.provider.BaseballCardProvider:   sortOrder=null
    01-25 02:46:21.868  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:   cursor=android.content.ContentResolver$CursorWrapperInner@422ac1b0
    01-25 02:46:21.868  2562  2671 D bbct.android.common.provider.SingleColumnCursorAdapter:     # of rows=0
    01-25 02:46:22.923  2562  2562 E MonitoringInstrumentation: java.lang.IllegalStateException: trying to requery an already closed cursor  android.content.ContentResolver$CursorWrapperInner@422677b8

**Comment by codeguru42** [comment]
#345 Should fix this. I still need to verify the fix by making `BaseballCardDetailsSleepTest.testSleep()` fail at 1f8e9eb and pass at 0089efd

**Comment by codeguru42** [comment]
Testing not complete. Will revisit when I can run tests on a device.
