### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'boolean android.widget.EditText.isEnabled()' on a null object reference

### ISSUE THREAD

**Issue by codeguru42** [BaseballCardTracker/bbct#329]
## Google Play Crash Report

**Device:** Galaxy S6 (zerofltespr)

**Android Version:** 5.1

**App Version:** 15 (Lite)

**User Message:**
> Crashed click link

**Stack Trace:**
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.widget.EditText.isEnabled()' on a null object reference
        at bbct.android.common.activity.FilterCards.onSaveInstanceState(FilterCards.java:83)
        at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:1647)
        at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1621)
        at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1689)
        at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:546)
        at android.app.Activity.performSaveInstanceState(Activity.java:1431)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1302)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:5122)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4458)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4521)
        at android.app.ActivityThread.access$1300(ActivityThread.java:198)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6837)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by codeguru42** [comment]
## Google Play Crash Report

**Device:** Galaxy S3 (d2lterefreshspr)

**Android Version:** 4.4

**App Version:** 15 (Lite)

**User Message:**
none

**Stack Trace:**

    java.lang.NullPointerException
        at bbct.android.common.activity.FilterCards.onSaveInstanceState(FilterCards.java:83)
        at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:1647)
        at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1621)
        at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1689)
        at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:546)
        at android.app.Activity.performSaveInstanceState(Activity.java:1229)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1229)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3390)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.access$1200(ActivityThread.java:169)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1302)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5487)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by codeguru42** [comment]
As I have been working on the tests, I accidentally recreated this problem

https://github.com/codeguru42/bbct/blob/6836d7d78d58572b6ce12fa8dd79d28ae8e75e64/gradle/android/src/androidTest/java/bbct/android/common/activity/test/BaseballCardListWithDataTest.java#L179-L184
