### ISSUE TITLE
NullPointerException in FilterCards.onSaveInstanceState()

### ISSUE THREAD

**Issue by codeguru42** [BaseballCardTracker/bbct#330]
## Google Play Crash Report

**Device:** Galaxy S3 (d2lterefreshspr)

**Android Version:** 4.4

**App Version:** 15 (Lite)

**User Message:**
none

**Stack Trace:**

    java.lang.NullPointerException
        at bbct.android.common.activity.FilterCards.onSaveInstanceState(FilterCards.java:83)
        at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:1647)
        at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1621)
        at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1689)
        at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:546)
        at android.app.Activity.performSaveInstanceState(Activity.java:1229)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1229)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3390)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.access$1200(ActivityThread.java:169)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1302)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5487)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by codeguru42** [comment]
Duplicate #328
