### ISSUE TITLE
NumberFormatException: Invalid double: ""

### ISSUE THREAD

**Issue by codeguru42** [BaseballCardTracker/bbct#356]
## Google Play Crash Report

**Device:** Galaxy Tab4 8.0 (milletlteatt)

**Android Version:** Android 4.4

**App Version:** 17 (Lite)

**User Message:** none

**Stack Trace:**

    java.lang.NumberFormatException: Invalid double: ""
        at java.lang.StringToReal.invalidReal(StringToReal.java:63)
        at java.lang.StringToReal.initialParse(StringToReal.java:163)
        at java.lang.StringToReal.parseDouble(StringToReal.java:263)
        at java.lang.Double.parseDouble(Double.java:295)
        at bbct.android.common.activity.BaseballCardDetails.getBaseballCard(BaseballCardDetails.java:279)
        at bbct.android.common.activity.BaseballCardDetails.onSave(BaseballCardDetails.java:306)
        at bbct.android.common.activity.BaseballCardDetails.onOptionsItemSelected(BaseballCardDetails.java:219)
        at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2070)
        at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2159)
        at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:295)
        at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:367)
        at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:147)
        at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
        at android.support.v7.app.AppCompatDelegateImplV7.onMenuItemSelected(AppCompatDelegateImplV7.java:620)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:618)
        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
        at android.view.View.performClick(View.java:4637)
        at android.view.View$PerformClick.run(View.java:19422)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5479)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by jojonarte** [comment]
Investigating this.

**Comment by codeguru42** [comment]
@jojonarte Note the empty string in the error message. This should be handled more gracefully with a proper message to the user.
